config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  
  root to: 'users#index'


  resources :users, only: [:index, :show] do
    resources :posts, only: [:index, :show, :new, :create, :destroy] do
      resources :comments, only: [:new, :create, :destroy]
      resources :likes, only: [:create]
    end
  end

  # Resources for the API
 namespace :api do
    resources :users, only: [] do
      resources :posts, only: [:index] do
        resources :comments, only: [:index, :create]
      end
    end
  end
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    user ||= User.new

    if user.admin?
      can :manage, :all
    else
      can :read, :all
      can :manage, Post, author_id: user.id
      can :manage, Comment, author_id: user.id
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :author, class_name: 'User', foreign_key: 'author_id'
  belongs_to :post, class_name: 'Post', foreign_key: 'post_id'

  after_save :update_comments_counter

  private

  def update_comments_counter
    post.increment!(:comments_counter)
  end
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :author, class_name: 'User', foreign_key: 'author_id'
  belongs_to :post, class_name: 'Post', foreign_key: 'post_id'

  after_save :update_likes_counter

  private

  def update_likes_counter
    post.increment!(:likes_counter)
  end
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :author, class_name: 'User', foreign_key: 'author_id'
  has_many :comments, class_name: 'Comment', foreign_key: 'post_id', dependent: :destroy
  has_many :likes, class_name: 'Like', foreign_key: 'post_id', dependent: :destroy

  after_save :update_posts_counter

  validates :text, presence: true
  validates :title, presence: true, length: { in: 3..250 }
  validates :comments_counter, presence: true, numericality: { only_integer: true, greater_than_or_equal_to: 0 }
  validates :likes_counter, presence: true, numericality: { only_integer: true, greater_than_or_equal_to: 0 }

  def recent_comments
    comments.includes(:author).order(created_at: :desc).limit(5)
  end

  private

  def update_posts_counter
    author.increment!(:posts_counter)
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :confirmable

  has_many :comments, class_name: 'Comment', foreign_key: 'author_id'
  has_many :posts, class_name: 'Post', foreign_key: 'author_id'
  has_many :likes, class_name: 'Like', foreign_key: 'author_id'

  validates :name, presence: true, length: { in: 3..30 }
  validates :posts_counter, presence: true, numericality: { only_integer: true, greater_than_or_equal_to: 0 }

  def admin?
    role == 'admin'
  end

  def recent_posts
    posts.order(created_at: :desc).limit(3)
  end
end

app/controllers/api/application_controller.rb
class Api::ApplicationController < ApplicationController
  rescue_from CanCan::AccessDenied do |exception|
    redirect_to root_url, alert: exception.message
  end

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: %i[email name password password_confirmation])
  end
end

app/controllers/api/comments_controller.rb
class Api::CommentsController < Api::ApplicationController
  def index
    post = Post.find(params[:post_id])
    comments = post.comments
    render json: comments
  end

  def create
    post = Post.find(params[:post_id])
    comment = post.comments.build(comment_params)
    comment.user = current_user

    if comment.save
      render json: comment, status: :created
    else
      render json: { error: 'Comment cannot be added.' }, status: :unprocessable_entity
    end
  end

  private

  def comment_params
    params.require(:comment).permit(:content)
  end
end

app/controllers/api/post_controller.rb
class Api::PostsController < Api::ApplicationController
  def index
    user = User.find(params[:user_id])
    posts = user.posts
    render json: posts
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # def current_user
  #   User.first
  # end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  load_and_authorize_resource
  def new
    @comment = Comment.new
  end

  def create
    @comment = Comment.new(comment_params)
    @comment.author = current_user
    @comment.post = Post.find(params[:post_id])
    respond_to do |_format|
      if @comment.save
        redirect_to user_post_path(user_id: params[:user_id], id: params[:post_id])
      else
        render :new
      end
    end
  end

  def destroy
    @comment = Comment.find(params[:id])
    if @comment.destroy
      redirect_to user_post_path(user_id: current_user.id, id: @comment.post_id), notice: 'Comment deleted successfully'
    else
      flash.new[:alert] = @comment.errors.full_messages.first if @comment.errors.any?
      render :show, status: 400
    end
  end

  private

  def comment_params
    params.require(:comment).permit(:text)
  end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  def create
    @like = Like.new
    @like.author = current_user
    @like.post = Post.find(params[:post_id])
    @like.save!
    redirect_to user_post_path(user_id: params[:user_id], id: params[:post_id])
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  load_and_authorize_resource

  def index
    @posts = Post.includes(:comments).where(author_id: params[:user_id])
    @user = User.find(params[:user_id])
  end

  def show
    @post = Post.find(params[:id])
    @user = @post.author
  end

  def new
    @post = Post.new
  end

  def create
    puts 'Current User'

    @post = Post.new(post_params)
    @post.author = current_user

    respond_to do |_format|
      if @post.save
        redirect_to user_posts_path(current_user)
      else
        render :new
      end
    end
  end

  def destroy
    @post = Post.find(params[:id])

    if @post.destroy
      redirect_to user_posts_path(current_user), notice: 'Post deleted successfully'
    else
      flash.new[:alert] = @post.errors.full_messages.first if @post.errors.any?
      render :show, status: 400
    end
  end

  private

  def post_params
    params.require(:post).permit(:title, :text)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all.order(id: :asc)
  end

  def show
    @user = User.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/comments/new.html.erb
<section class="new-comment-container">
  <%= form_with model: @comment, url: user_post_comments_path, local: true do |form| %>
    <%= form.text_field :text, class: "comment-field", placeholder: "Enter a text here" %>
    <%= form.submit "Add comment", class: "submit-btn btn" %>
  <% end %>
</section>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BlogApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "app", "data-turbo-track": "reload" %>
    <%= stylesheet_link_tag "post", "data-turbo-track": "reload" %>
    <%= stylesheet_link_tag "comment", "data-turbo-track": "reload" %>
    <%= stylesheet_link_tag "login", "data-turbo-track": "reload" %>
     <%= stylesheet_link_tag "signup", "data-turbo-track": "reload" %>
      <%= stylesheet_link_tag "password", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
       <p class="notice"><%= notice %></p>
       <p class="alert"><%= alert %></p>
      <%= yield %>
  </body>
</html>

app/views/posts/index.html.erb
<%= render 'shared/user', user: @user %>

<div class='index-box'>
  <% @posts.each do |post| %>
    <div class='box comments-box'>
      <a href='/users/<%= post.author_id%>/posts/<%= post.id%>'><%= post.title%></a>
      <p>
        <%= post.text%>
      </p>
      <p class='counters'>Comments: <%= post.comments_counter %> Likes: <%= post.likes_counter %></p>
  </div>
          <div>
  <% if can? :delete, @post %>
    <button type="button" class="delete_btn btn"><%= link_to "Delete Post", user_post_path(user_id: @post.author.id, id: @post.id), data: { turbo_method: :delete } %></button>
  <% end %>
          </div>
  <div class='box'>
  <% post.recent_comments.each do |comment| %>
      <p><%= comment.author.name %> - <%= comment.text %></p>
    <% end %>
  </div>
  <br />
  <% end %>
  <div class='btn'>
    <button class='pagination'>Pagination</button>
  </div>
</div>

app/views/posts/new.html.erb
<section class="new-post-container">
  <%= render partial: "shared/form", locals: { post: @post } %> 
</section>

app/views/posts/show.html.erb
<div class='show-container'>
  <div class='box'>
    <div class='posts-container'>
      <p><%= @post.title %> by <%= @post.author.name %></p>
    </div>
    <p>
      <%= @post.text %>
    </p>
  </div>
  <br />
  
  <div class='box'>
    <% @post.comments.each do |comment| %>
      <p><%= comment.author.name %>: <%= comment.text %></p>
      <% if can? :destroy, comment %>
        <%= link_to "Delete Comment", user_post_comment_path(user_id: comment.author.id, post_id: @post.id, id: comment.id), data: { turbo_method: :delete }, class:'button_style' %>
      <% end %>
    <% end %>
  </div>
  <p>Comments: <%= @post.comments_counter %> Likes: <%= @post.likes_counter %></p>
  <button type="button" class="create-post-btn btn">
    <%= link_to "Add a new comment", new_user_post_comment_path(user_id: @post.author.id, post_id: @post.id) %>
  </button>
   <%= render partial: "shared/like", locals: { like: Like.new, post_id: @post.id, user_id: @post.author.id } %>
</div>

app/views/shared/_form.html.erb
<%= form_with model: @post, url: user_posts_path, local: true do |form| %>
  <%= form.text_field :title, class: "form-title", placeholder: "Enter a title here" %>
  <%= form.text_area :text, class: "form-text", placeholder: "Enter a text here" %>
  <%= form.submit "Submit", class: "submit-btn btn" %>
<% end %>

app/views/shared/_like.html.erb
<section class="new_like">
  <%= form_with model: @like, url: user_post_likes_path(user_id: @user, post_id: @post), local: true do |form| %>
    <%= form.submit "Like", class: "like-btn btn" %>
  <% end %>
</section>

app/views/shared/_user.html.erb
<div class='main'>
  <div class='box img-box'>
     <% if user.photo? %>
      <img src=<%= user.photo%> alt="<%= user.name %>'s photo">
    <% else %>
        <%= image_tag "https://cdn.pixabay.com/photo/2015/10/05/22/37/blank-profile-picture-973460_960_720.png" %>
    <% end %>
  </div>
  <div class='box my-card'>
    <a href='/users/<%= user.id %>'>
      <h2 class='title'><%= user.name %></h2>
    </a>
    <p class='posts-counter '>
      Total number of posts are: <%= user.posts_counter %>
    </p>
  </div>
</div>

app/views/users/index.html.erb
<% @users.each do |user| %>
    <%= render partial: 'shared/user', locals: { user: user } %>
<% end %>

app/views/users/show.html.erb
<%= render 'shared/user', user: @user %>

<div class='info'>
  <div class='box'>
    <h1>Bio</h1>
    <p>
      <%= @user.bio %>
    </p>
  </div>

  <% @user.recent_posts.each do |post| %>
    <div class='box'>
      <h2><%= link_to post.title, user_post_path(user_id: post.author_id, id: post.id) %></h2>
      <p>
        <%= post.text %>
      </p>
      <p class='counters'>Comments: <%= post.comments_counter %> Likes: <%= post.likes_counter %></p>
    </div>
  <% end %>

  <a href='/users/<%= @user.id%>/posts' class='show-all btn'>Show All</a>
  <button type="button" class="create-post btn"><%= link_to "Create Post", new_user_post_path(@user) %></button>
</div>